name: "Python Build and Test"
description: "Set up Python, install dependencies, and run tests with environment info"
author: "mhmusic"

inputs:
  environment:
    description: "The environment to run on"
    required: true
  python-version:
    description: "Python version to use"
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      shell: bash
      run: |
        echo "Running tests for environment: ${{ inputs.environment }}"
        echo "Using Python version ${{ steps.setup-python.outputs.python-version }}"
