name: Reusable Python Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to run on'
        type: choice
        options:
          - dev
          - staging
          - prod
        required: true
      python-version:
        description: 'Python version to use'
        type: string
        required: false
        default: '3.10'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          echo "Running tests for environment: ${{ inputs.environment }}"
          # Replace with your actual test command, e.g., pytest
          echo "Using Python version ${{ steps.setup-python.outputs.python-version }}"